// AI 模型排行榜快照(自动生成自 thirdhub.pages.dev/js/ai/ai-rankings.js)
const kRankDims = [ '代码', '数学', '中文', '创意', '指令', '多轮' ];
const kRankCategories = [
  ('overall', '综合榜'),
  ('code', '代码榜'),
  ('english', '英文榜'),
  ('hard', '困难提示'),
  ('chinese', '中文榜'),
  ('multi', '多轮对话'),
  ('writing', '创意写作'),
  ('math', '数学榜'),
  ('instruct', '指令遵循'),
  ('japanese', '日语榜'),
  ('korean', '韩语榜'),
];
const kRankings = <String, List<Map<String, dynamic>>>{
  'overall': [
    <String, dynamic>{'m': 'Gemini 3.1 Pro', 'p': 'google', 's': 96, 'dims': <int>[93, 96, 88, 90, 93, 92]},
    <String, dynamic>{'m': 'GPT-5.2', 'p': 'openai', 's': 95, 'dims': <int>[94, 95, 86, 92, 95, 94]},
    <String, dynamic>{'m': 'Claude Opus 5', 'p': 'anthropic', 's': 95, 'dims': <int>[96, 92, 87, 95, 94, 93]},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 93, 'dims': <int>[88, 91, 82, 88, 87, 88]},
    <String, dynamic>{'m': 'Kimi K3', 'p': 'moonshot', 's': 92, 'dims': <int>[89, 90, 92, 91, 90, 91]},
    <String, dynamic>{'m': 'DeepSeek V4', 'p': 'deepseek', 's': 91, 'dims': <int>[90, 93, 94, 89, 88, 89]},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 90, 'dims': <int>[91, 89, 93, 85, 89, 88]},
    <String, dynamic>{'m': 'GLM-5.2', 'p': 'zhipu', 's': 89, 'dims': <int>[88, 86, 91, 87, 86, 86]},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 88, 'dims': <int>[87, 84, 85, 84, 84, 84]},
    <String, dynamic>{'m': '豆包 Seed 1.6', 'p': 'bytedance', 's': 87, 'dims': <int>[83, 82, 90, 85, 85, 85]},
    <String, dynamic>{'m': 'MiMo v2.5 Pro', 'p': 'xiaomi', 's': 86, 'dims': <int>[84, 87, 86, 82, 83, 82]},
    <String, dynamic>{'m': '混元 T1', 'p': 'tencent', 's': 85, 'dims': <int>[81, 84, 88, 82, 82, 81]},
  ],
  'code': [
    <String, dynamic>{'m': 'Claude Opus 5', 'p': 'anthropic', 's': 96},
    <String, dynamic>{'m': 'GPT-5.2', 'p': 'openai', 's': 94},
    <String, dynamic>{'m': 'Gemini 3.1 Pro', 'p': 'google', 's': 93},
    <String, dynamic>{'m': 'Qwen3 Coder Plus', 'p': 'aliyun', 's': 92},
    <String, dynamic>{'m': 'DeepSeek V4', 'p': 'deepseek', 's': 90},
    <String, dynamic>{'m': 'Kimi K3', 'p': 'moonshot', 's': 89},
    <String, dynamic>{'m': 'GLM-5.2', 'p': 'zhipu', 's': 88},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 87},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 86},
    <String, dynamic>{'m': 'Codestral 25.08', 'p': 'mistral', 's': 84},
  ],
  'english': [
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 96},
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 95},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 94},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 92},
    <String, dynamic>{'m': 'Llama 4 Maverick', 'p': 'groq', 's': 88},
    <String, dynamic>{'m': 'Mistral Large 3', 'p': 'mistral', 's': 86},
    <String, dynamic>{'m': 'Command R+', 'p': 'cohere', 's': 84},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 84},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 83},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 82},
  ],
  'hard': [
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 95},
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 94},
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 94},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 91},
    <String, dynamic>{'m': 'Kimi K2 Thinking', 'p': 'moonshot', 's': 90},
    <String, dynamic>{'m': 'DeepSeek R1', 'p': 'deepseek', 's': 89},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 87},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 86},
    <String, dynamic>{'m': '混元 T1', 'p': 'tencent', 's': 84},
    <String, dynamic>{'m': 'MiMo v2.5 Pro', 'p': 'xiaomi', 's': 83},
  ],
  'chinese': [
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 94},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 93},
    <String, dynamic>{'m': 'Kimi K2 Thinking', 'p': 'moonshot', 's': 92},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 91},
    <String, dynamic>{'m': '豆包 Seed 1.6', 'p': 'bytedance', 's': 90},
    <String, dynamic>{'m': '混元 T1', 'p': 'tencent', 's': 88},
    <String, dynamic>{'m': '文心 4.5 Turbo', 'p': 'baidu', 's': 87},
    <String, dynamic>{'m': 'MiMo v2.5 Pro', 'p': 'xiaomi', 's': 86},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 85},
    <String, dynamic>{'m': '讯飞星火 4.0', 'p': 'spark', 's': 84},
  ],
  'multi': [
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 94},
    <String, dynamic>{'m': 'Claude Sonnet 4.5', 'p': 'anthropic', 's': 93},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 92},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 91},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 89},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 88},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 87},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 86},
    <String, dynamic>{'m': '豆包 Seed 1.6', 'p': 'bytedance', 's': 85},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 84},
  ],
  'writing': [
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 95},
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 92},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 91},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 90},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 89},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 87},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 86},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 85},
    <String, dynamic>{'m': '文心 4.5 Turbo', 'p': 'baidu', 's': 84},
    <String, dynamic>{'m': 'Mistral Large 3', 'p': 'mistral', 's': 82},
  ],
  'math': [
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 96},
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 95},
    <String, dynamic>{'m': 'DeepSeek R1', 'p': 'deepseek', 's': 93},
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 92},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 91},
    <String, dynamic>{'m': 'Kimi K2 Thinking', 'p': 'moonshot', 's': 90},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 89},
    <String, dynamic>{'m': 'MiMo v2.5 Pro', 'p': 'xiaomi', 's': 87},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 86},
    <String, dynamic>{'m': '混元 T1', 'p': 'tencent', 's': 84},
  ],
  'instruct': [
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 95},
    <String, dynamic>{'m': 'Claude Sonnet 4.5', 'p': 'anthropic', 's': 94},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 93},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 90},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 89},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 88},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 87},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 86},
    <String, dynamic>{'m': '豆包 Seed 1.6', 'p': 'bytedance', 's': 85},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 84},
  ],
  'japanese': [
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 93},
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 92},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 91},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 88},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 85},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 84},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 83},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 81},
    <String, dynamic>{'m': 'Mistral Large 3', 'p': 'mistral', 's': 79},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 78},
  ],
  'korean': [
    <String, dynamic>{'m': 'GPT-5.1', 'p': 'openai', 's': 92},
    <String, dynamic>{'m': 'Claude Opus 4.5', 'p': 'anthropic', 's': 91},
    <String, dynamic>{'m': 'Gemini 3 Pro', 'p': 'google', 's': 90},
    <String, dynamic>{'m': 'Grok 4.1', 'p': 'xai', 's': 87},
    <String, dynamic>{'m': 'DeepSeek V3.2', 'p': 'deepseek', 's': 84},
    <String, dynamic>{'m': 'Qwen3 Max', 'p': 'aliyun', 's': 83},
    <String, dynamic>{'m': 'Kimi K2', 'p': 'moonshot', 's': 82},
    <String, dynamic>{'m': 'GLM-4.6', 'p': 'zhipu', 's': 80},
    <String, dynamic>{'m': 'MiniMax M2', 'p': 'minimax', 's': 77},
    <String, dynamic>{'m': 'Mistral Large 3', 'p': 'mistral', 's': 76},
  ],
};
